version: "3.9"
services:
  python3:
    build: ./python3
    restart: always
    volumes:
      - ./python3/root_jupyter:/root/.jupyter
      - ./workspace:/workspace
    ports:
      - "8888:8888"
    entrypoint: >
      jupyter-lab
      --allow-root
      --ip=0.0.0.0
      --port=8888
      --no-browser
      --notebook-dir=/workspace
